import type { Game } from './types'

export const GAMES: Game[] = [
  {
    id: 'pong',
    name: 'Neón Pong',
    tagline: 'El clásico, con luces de bar',
    emoji: '🏓',
    accent: 'blue',
    category: 'arcade',
    playable: true,
    players: '1v1',
    difficulty: 1,
    description: 'Duelo de palas a velocidad creciente. El primero en llegar a 7 se lleva el bote.',
  },
  {
    id: 'billar',
    name: 'Billar de Trastienda',
    tagline: 'Apunta, calcula, embolsa',
    emoji: '🎱',
    accent: 'green',
    category: 'mesa',
    playable: true,
    players: '1v1',
    difficulty: 2,
    description: 'Billar arcade simplificado. Mete tus bolas antes que el rival con la física de la mesa.',
  },
  {
    id: 'reflejos',
    name: 'Mano Fría',
    tagline: 'El más rápido del bar',
    emoji: '⚡',
    accent: 'red',
    category: 'reflejos',
    playable: true,
    players: '1v1',
    difficulty: 1,
    description: 'Cuando el neón cambie a verde, dispara. Falla antes y pierdes la ronda.',
  },
  {
    id: 'dardos',
    name: 'Dardos Clandestinos',
    tagline: 'Diana o nada',
    emoji: '🎯',
    accent: 'amber',
    category: 'mesa',
    playable: true,
    players: '1v1',
    difficulty: 2,
    description: 'Diana móvil con multiplicadores. Cuenta atrás desde 301.',
  },
  {
    id: 'airhockey',
    name: 'Air Hockey Neón',
    tagline: 'Disco al rojo vivo',
    emoji: '🥅',
    accent: 'purple',
    category: 'arcade',
    playable: true,
    players: '1v1',
    difficulty: 2,
    description: 'Defiende tu portería y mete 7 antes que el rival sobre una mesa de aire luminosa.',
  },
  {
    id: 'farol',
    name: 'El Farol',
    tagline: 'Miente con estilo',
    emoji: '🃏',
    accent: 'red',
    category: 'cartas',
    playable: false,
    players: '2-4',
    difficulty: 3,
    description: 'Cartas rápidas de farol y mentira. Pillado mintiendo, pagas el bote.',
  },
  {
    id: 'ppt',
    name: 'PPT Maestro',
    tagline: 'Piedra, papel o tijera evolucionado',
    emoji: '✊',
    accent: 'green',
    category: 'reflejos',
    playable: false,
    players: '1v1',
    difficulty: 1,
    description: 'Mejor de 5 con comodines y dobles. Lectura mental pura.',
  },
  {
    id: 'penaltis',
    name: 'Penaltis a Medianoche',
    tagline: 'Tú tiras, tú paras',
    emoji: '⚽',
    accent: 'green',
    category: 'arcade',
    playable: true,
    players: '1v1',
    difficulty: 2,
    description: 'Tanda de penaltis. Elige esquina y reza.',
  },
  {
    id: 'carreras',
    name: 'Carrera de Callejón 3D',
    tagline: 'Acelera o paga · en 3D',
    emoji: '🏎️',
    accent: 'blue',
    category: 'arcade',
    playable: true,
    players: '1v1',
    difficulty: 2,
    description: 'Sprint 1v1 en 3D esquivando obstáculos de neón. Cambia de carril y llega antes que el rival.',
  },
  {
    id: 'dados',
    name: 'Dados de la Casa 3D',
    tagline: 'La suerte está echada · en 3D',
    emoji: '🎲',
    accent: 'amber',
    category: 'azar',
    playable: true,
    players: '1v1',
    difficulty: 1,
    description: 'Dados en 3D con luces de neón. Lanza, suma más que el rival y llévate la ronda. Al mejor de 5.',
  },
  {
    id: 'bolos',
    name: 'Bolos Neón 3D',
    tagline: 'Pleno o nada',
    emoji: '🎳',
    accent: 'purple',
    category: 'arcade',
    playable: true,
    players: '1v1',
    difficulty: 2,
    description: 'Bolera 3D con luces de neón. Ajusta puntería y potencia, derriba más bolos que el rival.',
  },
  {
    id: 'ruleta',
    name: 'Ruleta de Retos',
    tagline: 'Solo demo, sin dinero real',
    emoji: '🎡',
    accent: 'purple',
    category: 'azar',
    playable: false,
    players: '2+',
    difficulty: 1,
    description: 'Gira para asignar retos divertidos al grupo. Nunca con dinero real.',
  },
]

export const getGame = (id: string) => GAMES.find((g) => g.id === id)

export const accentClasses: Record<
  Game['accent'],
  { text: string; border: string; glow: string; bg: string; from: string }
> = {
  red: {
    text: 'text-neon-red',
    border: 'border-neon-red/40',
    glow: 'shadow-neon-red',
    bg: 'bg-neon-red/10',
    from: 'from-neon-red/20',
  },
  purple: {
    text: 'text-neon-purple',
    border: 'border-neon-purple/40',
    glow: 'shadow-neon-purple',
    bg: 'bg-neon-purple/10',
    from: 'from-neon-purple/20',
  },
  blue: {
    text: 'text-neon-blue',
    border: 'border-neon-blue/40',
    glow: 'shadow-neon-blue',
    bg: 'bg-neon-blue/10',
    from: 'from-neon-blue/20',
  },
  green: {
    text: 'text-neon-green',
    border: 'border-neon-green/40',
    glow: 'shadow-neon-green',
    bg: 'bg-neon-green/10',
    from: 'from-neon-green/20',
  },
  amber: {
    text: 'text-neon-amber',
    border: 'border-neon-amber/40',
    glow: 'shadow-[0_0_18px_rgba(255,182,39,0.5)]',
    bg: 'bg-neon-amber/10',
    from: 'from-neon-amber/20',
  },
}
